### PR TITLE
Xian Liu Check In

### PR DESCRIPTION
**Pull request by xianliu**
Hi,

Please add me to the roster!

Here is my [Fedora Wiki user page](https://fedoraproject.org/wiki/User:Lxjsj) FYI.

### CODE REVIEW

**Comment by alick** [comment]
Hi xianliu,

Seems there is some conflict with the master branch. Can you fix it and update the PR?

**Comment by sztsian** [comment]
@xianliu  I thought you were already there in the roster before  :( Anyway, please fix it and I'll add you to the org.

**Comment by xianliu** [comment]
Got it, I created a new PR

**Comment by sztsian** [comment]
Closed as #30 merged

**Pull request closed without merging**
