### PR TITLE
Add gbraad and some linguistic improvements

### PR DESCRIPTION
**Pull request by gbraad**

### CODE REVIEW

**Comment by tvvocold** [comment]
@gbraad 
Welcome back :smile:

**Comment by gbraad** [comment]
I never left... 'lurking'... ;-)

**Comment by tvvocold** [comment]
hi @sztsian,
我建议添加 @gbraad 到 @FZUG/tier1 :)

**Comment by sztsian** [comment]
@tvvocold Done. I thought he was already there before.

**Comment by tvvocold** [comment]
@sztsian ，
Cool！

**Pull request merged**
