### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by FiveYellowMice**
Hi,

Please add me to the roster!

Here is my [Fedora Wiki user page][userpage] FYI.

[userpage]: https://fedoraproject.org/wiki/User:fiveyellowmice

### CODE REVIEW

**Comment by sztsian** [comment]
Hi @FiveYellowMice ,
I see your Fedora User page do not exists. Have you registered in Fedora Account System?

**Comment by cicku** [comment]
Who are you?

**Comment by FiveYellowMice** [comment]
I did register on FAS. But since I'm not in a group besides CLA, I don't get the privilege to edit wiki.

To prove I have a FAS account, this is [my COPR profile](https://copr.fedorainfracloud.org/coprs/fiveyellowmice/).

**Comment by FiveYellowMice** [comment]
@cicku I'm FiveYellowMice, obviously.

**Comment by cicku** [comment]
I never see you active in FZUG mailing list, thus there is no reason adding you to this repo.

**Comment by FiveYellowMice** [comment]
Alright, I thought it was open for everyone to join.

**Comment by alick** [comment]
@FiveYellowMice This repo is meant to map FZUG members on GitHub to FAS. It is good to have you in.

You're saying you cannot even edit your own user page on wiki? I believe this is a bug, and will ask on the mailing list.

**Comment by alick** [comment]
@FiveYellowMice Seems requiring CLA+1 to edit wiki is a recent change by infra to counter spams. You are suggested to join one of the several contributor groups in Fedora, e.g. L10N for translation. After that you should have enough privilege to edit wiki pages.

**Comment by cicku** [comment]
No offense, this place is not for swag, if you just want a group icon in your github profile to show off, please find another one.

**Comment by alick** [comment]
@cicku Watch your mouth!

**Comment by FiveYellowMice** [comment]
@cicku No, it's not what I will do. I just want to get help from and
contribute to the community. If that is not welcomed, I will not insist.

**Comment by cicku** [comment]
If so, you can join FZUG mailing list, sending us a brief introduction and start contribution.

See this page if you have interest, since most of guides are available at here: https://fedoraproject.org/wiki/Join

**Comment by cicku** [comment]
@alick

Sorry about that, I just want to make sure if he really wants to join. It's the principle, right?

**Comment by sztsian** [comment]
I have no objections to add merge requests on this just for mapping FAS vs Github username. But I will not add non-active contributor to the team. And I am cleaning up non-active members out of the org sometimes, since as a member to the org the user possibly gain other 'permission' or so.

@FiveYellowMice First thanks for your interest in Fedora. as cicku replies, please join the Fedora Chinese Mailing list and do a brief self-introduction at least. CLA+1 means you should already start contributing to Fedora and is sponsored into some contributor team. That is the basic requirements for editing Fedora wiki now.

**Comment by FiveYellowMice** [comment]
@alick @sztsian Thank you for the suggestions.

**Comment by alick** [comment]
Sorry I might have overreacted. I just don't want newcomers feel unwelcome.

Regards,

**Pull request closed without merging**
