### PR TITLE
Add user suiwenfeng

### PR DESCRIPTION
**Pull request by ghost**
Hi,

Please add me to the roster!

Here is my [Fedora Wiki user page][userpage] FYI.

[userpage]: https://fedoraproject.org/wiki/User:suiwenfeng

### CODE REVIEW

**Comment by alick** [comment]
Welcome!

**Comment by ghost** [comment]
昨天刚刚加入Fedora QA Work Group， 我看到你一直在做翻译这块。有空可以更我讲下怎么入坑么？

我感兴趣的是Fedora Cloud这块，docker image类试coreos这样的。

**Comment by cheese** [comment]
可以看一下最近完成的 layered image 体系：
http://www.projectatomic.io/blog/2017/04/fedora-layered-images-april/
https://fedoraproject.org/wiki/Changes/Layered_Docker_Image_Build_Service
https://pagure.io/atomic-wg

**Comment by ghost** [comment]
@cheese 非常感谢

**Pull request merged**
