### PR TITLE
add yaochx into members

### PR DESCRIPTION
**Pull request by yaochx**

### CODE REVIEW

**Comment by alick** [comment]
https://fedoraproject.org/wiki/User:Chengxiang

```
User account "Chengxiang" is not registered. 
```

Please fix it.

**Comment by yaochx** [comment]
@alick Thanks for your kindly reminding. I'll fix it. Pls check it again.

**Comment by alick** [comment]
Looks good. Welcome on board!

**Comment by cicku** [comment]
Welcome.

**Pull request merged**
