### PR TITLE
新用户报道

### PR DESCRIPTION
**Pull request by vhtq18w**
Hi,

Please add me to the roster!

Here is my [Fedora Wiki user page][userpage] FYI.

[userpage]: https://fedoraproject.org/wiki/User:Vhtq18w

### CODE REVIEW

**Comment by sztsian** [comment]
Hi,

Your user page is not created. Please write a brief self-introduction on your Fedora user page so that community members can know who you are. After it's done, please comment on this PR again.

**Comment by cicku** [comment]
Please edit your userpage link, it's not `My_FAS_NAME`.

**Comment by sztsian** [comment]
> Please edit your userpage link, it's not My_FAS_NAME.

Tanks cicku. This actually comes from his comment message

@vHtQ18W Please fix your comment message as well.

**Comment by vhtq18w** [comment]
Now I' have finished edit my userpage.
And I'm sorry that there is no time in front to edit it :)

**Comment by alick** [comment]
@vHtQ18W I'll merge the PR. Note that you *can* edit your previous comments and commits to fix typos etc.

**Comment by alick** [comment]
If you are looking for ways to contribute to Fedora, check out http://whatcanidoforfedora.org/

中文交流，可以到[中文邮件列表](https://lists.fedoraproject.org/admin/lists/chinese.lists.fedoraproject.org/)。

**Pull request merged**
